// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcIZdX1KSFetOB8gmOZ5FKgGINbbqg01M',
    appId: '1:796033415270:web:6606eb02ffcf07af2315a7',
    messagingSenderId: '796033415270',
    projectId: 'to-doapp-e1437',
    authDomain: 'to-doapp-e1437.firebaseapp.com',
    storageBucket: 'to-doapp-e1437.firebasestorage.app',
    measurementId: 'G-F8D044Y2TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDugwQ4F3YAFX2NSQEvDdnBImxFSwo7854',
    appId: '1:796033415270:android:cb7063adaee64b192315a7',
    messagingSenderId: '796033415270',
    projectId: 'to-doapp-e1437',
    storageBucket: 'to-doapp-e1437.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDupeDJKMy5ZipiLUyqk8nwsZXfxHQ3PjU',
    appId: '1:796033415270:ios:5744dcbecd406ad02315a7',
    messagingSenderId: '796033415270',
    projectId: 'to-doapp-e1437',
    storageBucket: 'to-doapp-e1437.firebasestorage.app',
    iosBundleId: 'com.example.toDoUygulamsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDupeDJKMy5ZipiLUyqk8nwsZXfxHQ3PjU',
    appId: '1:796033415270:ios:5744dcbecd406ad02315a7',
    messagingSenderId: '796033415270',
    projectId: 'to-doapp-e1437',
    storageBucket: 'to-doapp-e1437.firebasestorage.app',
    iosBundleId: 'com.example.toDoUygulamsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcIZdX1KSFetOB8gmOZ5FKgGINbbqg01M',
    appId: '1:796033415270:web:1e5c01b4518e7e602315a7',
    messagingSenderId: '796033415270',
    projectId: 'to-doapp-e1437',
    authDomain: 'to-doapp-e1437.firebaseapp.com',
    storageBucket: 'to-doapp-e1437.firebasestorage.app',
    measurementId: 'G-87VRYW9204',
  );
}
